"use client";

import { Check, Copy, Download, FileText, ShieldAlert, ShieldCheck } from "lucide-react";
import React, { useState } from "react";
import { toast } from "sonner";

interface VideoReportSummaryProps {
  videoName: string;
  createdAt?: string | Date;
  summary: string;
  threatDetected?: boolean;
  onSeek?: (seconds: number) => void;
}

// Helper to convert "01:14" to 74 seconds
function parseTimestamp(ts: string): number {
  const [min, sec] = ts.split(':').map(Number);
  return min * 60 + sec;
}

export function VideoReportSummary({
  videoName,
  createdAt = new Date(),
  summary,
  threatDetected = false,
  onSeek,
}: VideoReportSummaryProps) {
  const [copied, setCopied] = useState(false);

  const formattedDate = new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
    hour12: true,
  }).format(new Date(createdAt));

  const exportPayload = `=====================================================
ESTATEVISION™ FOOTAGE AUDIT REPORT
=====================================================
Video: ${videoName}
Audit Timestamp: ${formattedDate}
Threat Status: ${threatDetected ? "CRITICAL / THREAT DETECTED" : "CLEAR / NO THREATS DETECTED"}
=====================================================

CHRONOLOGICAL EVENT BREAKDOWN & TRANSCRIPT:
${summary}

=====================================================
Generated by EstateVision CCTV Intelligence
`;

  function handleCopy() {
    navigator.clipboard.writeText(exportPayload);
    setCopied(true);
    toast.success("Report copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  }

  function handleExportFile() {
    const blob = new Blob([exportPayload], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    const sanitizedName = videoName.replace(/[^a-zA-Z0-9_-]/g, "_");
    link.href = url;
    link.download = `EstateVision_Audit_${sanitizedName}_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success("Report downloaded successfully");
  }

  // Regex parser to find MM:SS and convert to clickable buttons
  function renderInteractiveText(text: string) {
    if (!text) return null;
    const regex = /\b(\d{1,2}:\d{2})\b/g;
    const parts = text.split(regex);
    
    return parts.map((part, i) => {
      if (regex.test(part)) {
        return (
          <button
            key={i}
            type="button"
            onClick={() => onSeek?.(parseTimestamp(part))}
            className="mx-1 inline-flex items-center rounded bg-red-500/20 px-1.5 py-0.5 font-mono text-xs font-semibold text-red-400 transition-colors hover:bg-red-500/40 active:scale-95"
            title={`Jump to ${part}`}
          >
            {part}
          </button>
        );
      }
      return <React.Fragment key={i}>{part}</React.Fragment>;
    });
  }

  return (
    <div className="mt-6 overflow-hidden rounded-2xl border border-neutral-800 bg-neutral-950/70 p-5 backdrop-blur-md">
      {/* Header Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-neutral-800/80 pb-4">
        <div className="flex items-center gap-3">
          <div className="flex size-9 items-center justify-center rounded-lg border border-neutral-700 bg-neutral-800/50 text-neutral-200">
            <FileText className="size-4 text-red-500" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-neutral-100">
              Footage Intelligence Audit
            </h3>
            <p className="font-mono text-xs text-neutral-400">
              Timestamp: <span className="text-neutral-200">{formattedDate}</span>
            </p>
          </div>
        </div>

        {/* Threat Status Badge & Export Controls */}
        <div className="flex items-center gap-2">
          <span
            className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium ${
              threatDetected
                ? "border-red-500/30 bg-red-500/10 text-red-400"
                : "border-emerald-500/30 bg-emerald-500/10 text-emerald-400"
            }`}
          >
            {threatDetected ? (
              <>
                <ShieldAlert className="size-3.5" /> Threat Flagged
              </>
            ) : (
              <>
                <ShieldCheck className="size-3.5" /> No Threats
              </>
            )}
          </span>

          <button
            type="button"
            onClick={handleCopy}
            className="inline-flex h-8 cursor-pointer items-center gap-1.5 rounded-md border border-neutral-700 bg-neutral-800/70 px-3 text-xs font-medium text-neutral-200 transition-colors hover:bg-neutral-700 active:scale-95"
          >
            {copied ? (
              <>
                <Check className="size-3.5 text-emerald-400" /> Copied
              </>
            ) : (
              <>
                <Copy className="size-3.5" /> Copy
              </>
            )}
          </button>

          <button
            type="button"
            onClick={handleExportFile}
            className="inline-flex h-8 cursor-pointer items-center gap-1.5 rounded-md bg-red-600 px-3 text-xs font-medium text-white transition-colors hover:bg-red-700 active:scale-95"
          >
            <Download className="size-3.5" /> Export Report
          </button>
        </div>
      </div>

      {/* Summary Content Body */}
      <div className="mt-4">
        <div className="max-h-64 overflow-y-auto pr-2 text-sm leading-relaxed text-neutral-300">
          {summary ? (
            <p className="whitespace-pre-wrap">{renderInteractiveText(summary)}</p>
          ) : (
            <p className="italic text-neutral-500">
              Generating structured report from video telemetry...
            </p>
          )}
        </div>
      </div>
    </div>
  );
}